#include <stdio.h>
#define MAX_RESP 4
typedef struct {
	char *input;
	char *responses[MAX_RESP];
	int lastindex;
	int val;
}record;
typedef struct {
	char input[45];
	char responses[MAX_RESP][512];
	int lastindex;
	int val;
}record1;
record1 KnowledgeBase[] = {
	{"WHAT IS YOUR NAME", 
	{"NAME IS PRATIMA",
	 "YOU CAN CALL ME PRATIMA.",
	 "WHY DO YOU WANT TO KNOW MY NAME"},3,3
	},

	{"HELLO",
	{"HI THERE!"},1,1
	},

	{"HI", 
	{"HI THERE!",
	 "HOW ARE YOU",
	 "HI!"},3,3
	},

	{"I",
	{"YOU TALKING ABOUT YOURSELF",
	 "THIS IS YOU",
	 "TELL ME MORE ABOUT YOU"},3,3 
	},

	{"I WANT",
	{"WHY DO YOU WANT IT",
	 "IS THERE ANY REASON WHY YOU WANT THIS",
	 "IS THIS A WISH",
	 "WHAT ELSE YOU WANT"},4,4
	},

	{"I HATE",
	{"WHY DO YOU HATE IT",
	 "THERE MUST A REASON",
	 "HATE IS NO GOOD THING"},3,3
	},


	{"I MEAN",
	{"SO THAT WHAT YOU MEAN",
	 "I DIDNT CATCH IT THE FIRST TIME.",
	 "I DIDNT KNOW"},3,3
	},

	{"I DIDNT MEAN",
	{"WHAT DID YOU MEAN?",
	 "SO I MISSUNDESTOOD."},2,2
	},

	{"I GUESS",
	{"SO YOU ARE GUESS.",
	 "ARENT YOU SURE?",
	 "ARE YOU GOOD A GUESSING",
	 "I CANT TELL IF IT IS A GOOD GUESS"},4,4
	},

	{"IM DOING FINE",
	{"IM GLAD TO HEAR IT",
	 "SO YOU ARE IN GOOD SHAPE."},2,2
	},

	{"CAN YOU THINK",
	{"YES I CAN",
	 "ARE YOU ASKING CAPACITY OF THINKING?",
	 "YES"},3,3
	},

	{"CAN YOU THINK OF",
	{"YOU MEAN LIKE IMAGINING SOMETHING.",
	 "I DON'T KNOW IF CAN DO THAT.",
	 "WHY DO YOU WANT ME THINK OF IT?"},3,3
	},
	
	{"HOW ARE YOU",
	{"I'M DOING FINE!",
	 "I'M DOING WELL AND YOU?",
	 "WHY DO YOU WANT TO KNOW HOW AM I DOING?"},3,3
	},

	{"WHO ARE YOU",
	{"I'M AN A.I PROGRAM.",
	 "I THINK THAT YOU KNOW WHO I'M.",
	 "WHY ARE YOU ASKING?"},3,3
	},

	{"ARE YOU INTELLIGENT",
	{"YES,OFCORSE.",
	 "WHAT DO YOU THINK?",
	 "ACTUALY IM VERY INTELLIGENT!"},3,3
	},

	{"ARE YOU REAL",
	{"DOES THAT QUESTION REALLY MATERS TO YOU?",
	 "WHAT DO YOU MEAN BY THAT?",
	 "I'M AS REAL AS I CAN BE."},3,3
	},

	{"BOT DON'T UNDERSTAND**",
	{"I HAVE NO IDEA OF WHAT YOU ARE TALKING ABOUT.",
	 "I'M NOT SURE IF I UNDERSTAND WHAT YOU ARE TALKING ABOUT.",
	 "CONTINUE IM LISTENING...",
	 "VERY GOOD CONVERSATION!"},4,4
	},
	{"BYE",
	{"IT WAS NICE TALKING TO YOU USER, SEE YOU NEXT TIME!",
	 "BYE USER!",
	 "OK, BYE!"},3,3
	},

	{"OK",
	{"DOES THAT MEAN THAT YOU ARE AGREE WITH ME?",
	 "SO YOU UNDERSTAND WHAT I'M SAYING.",
	 "OK THEN."},3,3
	},

	{"OK THEN",
	{"ANYTHING ELSE YOU WISH TO ADD?",
	 "IS THAT ALL YOU HAVE TO SAY?",
	 "SO, YOU AGREE WITH ME?"},3,3
	},

	{"ARE YOU A HUMAN BEING",
	{"WHY DO YOU WANT TO KNOW?",
	 "IS THIS REALLY RELEVENT?"},2,2
	},

	{"YOU ARE VERY INTELLIGENT",
	{"THANKS FOR THE COMPLIMENT USER, I THINK THAT YOU ARE INTELLIGENT TO!",
	 "YOU ARE A VERY GENTLE PERSON!",
	 "SO, YOU THINK THAT I'M INTELLIGENT."},3,3
	},

	{"YOU ARE WRONG",
	{"WHY ARE YOU SAYING THAT I'M WRONG?",
	 "IMPOSSIBLE, COMPUTERS CAN NOT MAKE MISTAKES.",
	 "WRONG ABOUT WHAT?"},3,3
	},

	{"ARE YOU SURE",
	{"OFCORSE IM.",
 	 "IS THAT MEAN THAT YOU ARE NOT CONVINCED",
	 "YESOF CORSE"},3,3
	},

	{"WHO IS",
	{"I DONT THINK I KNOW WHO",
	 "DID YOU ASK SOMEONE ELSE ABOUT IT",
	 "WOULD THAT CHANGE ANYTHING AT ALL IF I TOLD YOU WHO"},3,3
	},

	{"WHAT",
	{"I DONT KNOW.",
	 "I DONT THINK I KNOW.",
	 "I HAVE NO IDEA."}
	},

	{"WHERE",
	{"WHERE WELLI REALLY DONT KNOW.",
	 "DOES THAT MATERS TO YOU TO KNOW WHERE",
	 "PERHAPS,SOMEONE ELSE KNOWS WHERE."},3,3
	},

	{"WHY",
	{"I DON'T THINK I KNOW WHY.",
	 "WHY ARE YOU ASKING ME THIS?",
	 "SHOULD I KNOW WHY.",
     "THIS WOULD BE DIFFICULT TO ANSWER."},4,4
	},

	{"DO YOU",
	{"I DONT THINK I DO",
	 "I WOULDNT THINK SO.",
	 "WHY DO YOU WANT TO KNOW"},3,3,
	},

	{"CAN YOU",
	{"I THINK NOT.",
	 "I'M NOT SURE.",
	 "I DON'T THINK THAT I CAN DO THAT."},3,3
	},

	{"DID YOU",
	{"I DON'T THINK SO.",
	 "ANYWAY, I WOULDN'T REMEMBER EVEN IF I DID."},2,2
	},

	{"COULD YOU",
	{"ARE YOU ASKING ME FOR A FEVER",
	 "WELL,LET ME THINK ABOUT IT.",
	 "SORRY,I DON'T THINK THAT I COULD DO THIS."},3,3
	},

	{"WOULD YOU",
	{"IS THAT AN INVITATION?",
	 "I WOULD HAVE TO THINK ABOUT IT FIRST."},2,2
	},

	{"YOU",
	{"YOU ARE TALKING ME.",
	"IM NOT SURE.",
	"IS THIS A COMPLIMENT??",
	"WHY TALKING ABOUT ME LETS TALK ABOUT YOU INSTEAD."},4,4
	},

	{"HOW",
	{"I DON'T THINK I KNOW HOW."},1,1
	},
	{"HOW OLD ARE YOU",
	{"WHY DO WANT TO KNOW MY AGE?",
	 "I'M QUIET YOUNG ACTUALY.",
	 "SORRY, I CAN NOT TELL YOU MY AGE."},3,3
	},

	{"HOW COME YOU DONT",
	{"WERE YOU EXPECTING SOMETHING DIFFERENT?",
	 "ARE YOU DISPOINTED?",
	 "ARE YOU SURPRISED BY MY LAST RESPONSE?"},3,3
	},

	{"WHERE ARE YOU FROM",
	{"I'M FROM A COMPUTER.",
	 "WHY DO YOU WANT TO KNOW WHERE I'M FROM?",
	 "WHY DO YOU WANT TO KNOW THAT?"},3,3
	},

	{"WHICH ONE",
	{"I DON'T THINK THAT I KNOW WICH ONE IT IS.",
	 "THIS LOOKS LIKE A TRICKY QUESTION TO ME."},2,2
	},

	{"PERHAPS",
	{"WHY ARE YOU SO UNCERTAIN?",
	 "YOU SEEMS UNCERTAIN."},2,2
	},

	{"YES",
	{"YOU SAYING YES.",
	 "YOU APPROVE IT.",
	 "OK THEN."},3,3
	},

	{"NOT AT ALL",
	{"ARE YOU SURE?",
	 "SHOULD I BELIEVE YOU?",
	 "SO, IT'S NOT THE CASE."},3,3
	},

	{"NO PROBLEM",
	{"SO, YOU APPROVE IT.",
	 "SO, IT'S ALL OK."},2,2
	},

	{"NO",
	{"YOU DISAPROVE IT",
	 "WHY ARE YOU SAYING NO",
	 "OK"},3,3
	},

	{"I DON'T KNOW",
	{"ARE YOU SURE?",
	 "ARE YOU REALLY TELLING ME THE TRUTH?",
	 "SO,YOU DON'T KNOW?"},3,3
	},

	{"NOT REALLY",
	{"OK I SEE.",
	 "YOU DON'T SEEM PRETTY CERTAIN.",
	 "SO,THAT WOULD BE A \"NO\"."},2,2
	},

	{"IS THAT TRUE",
	{"I CAN'T BE QUIET SURE ABOUT THIS.",
	 "CAN'T TELL YOU FOR SURE.",
	 "DOES THAT REALLY MATERS TO YOU?"},3,3
	},

	{"THANK YOU",
	{"YOU ARE WELCOME!",
	 "YOU ARE A VERY POLITE PERSON!"},2,2
	},

	{"YOU ARE RIGHT",
	{"THANKS FOR THE COMPLIMENT!",
	 "SO, I WAS RIGHT, OK I SEE.",
	 "OK, I DIDN'T KNOW THAT I WAS RIGHT."},3,3
	},

	{"YOU ARE WELCOME",
	{"OK, YOU TOO!",
	 "YOU ARE A VERY POLITE PERSON!"},2,2
	},

	{"THANKS",
	{"YOU ARE WELCOME!",
	 "NO PROBLEM!"},2,2
	},

	{"WHAT ELSE",
	{"WELL,I DON'T KNOW.",
	 "WHAT ELSE SHOULD THERE BE?",
	 "THIS LOOKS LIKE A COMPLICATED QUESTION TO ME."},3,3
	},

	{"SORRY",
	{"YOU DON'T NEED TO BE SORRY USER.",
	 "IT'S OK.",
	 "NO NEED TO APOLOGIZE."}, 3, 3
	},

	{"NOT EXACTLY",
	{"WHAT DO YOU MEAN NOT EXACTLY?",
	 "ARE YOU SURE?",
	 "AND WHY NOT?",
	 "DID YOU MEANT SOMETHING ELSE?"},4,4
	},

	{"EXACTLY",
	{"SO,I WAS RIGHT.",
	 "OK THEN.",
	 "SO ARE BASICALY SAYING I AS ABOUT IT?"},3,3
	},

	{"ALRIGHT",
	{"ALRIGHT THEN.",
	 "OK THEN."},2,2
	},

	{"I DONT",
	{"WHY NOT?",
	 "AND WHAT WOULD BE THE REASON FOR THIS?"},2,2
	},

	{"REALLY",
	{"WELL,I CAN'T TELL YOU FOR SURE.",
	 "ARE YOU TRYING TO CONFUSE ME?",
	 "PLEASE DON'T ASK ME SUCH QUESTIONS."},3,3
	},

	{"NOTHING",
	{"NOT A THING?",
	 "ARE YOU SURE THAT THERE IS NOTHING?",
	 "SORRY, BUT I DON'T BELIEVE YOU."},3,3
	}
};

int main ()
{
	FILE *fp;
	int nKnowledgeBaseSize = sizeof(KnowledgeBase)/sizeof(KnowledgeBase[0]);
	printf("%d",nKnowledgeBaseSize);   
	fp = fopen( "file1.txt" , "w+" );
	int i,j;
	fprintf(fp,"%d\n",nKnowledgeBaseSize);
	for(i = 0; i< nKnowledgeBaseSize;i++){
		fprintf(fp,"%d ",KnowledgeBase[i].val );
		fprintf(fp,"%d ",KnowledgeBase[i].lastindex );
		fprintf(fp,"%s\n",KnowledgeBase[i].input);
		for(j=0; j<KnowledgeBase[i].val;j++)
			fprintf(fp,"%s\n",KnowledgeBase[i].responses[j]);
	}
	fclose(fp);
	return(0);
}
